version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - instance_data:/app/instance
    command: >
      bash -c "python init_db.py &&
      python app.py"

volumes:
  app_data:
  instance_data: 