name: Lint Code

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install Node.js dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          else
            npm ci
          fi

      - name: Run Python linting
        run: |
          flake8 . --exclude=node_modules,venv,env,.git,__pycache__,build,dist,*.egg-info
          black . --exclude "/node_modules/" --check
          isort . --check --skip node_modules

      - name: Run JavaScript linting
        run: |
          npm run lint

      # Optional: Comment on PR with lint results
      - name: Comment on PR
        if: github.event_name == 'pull_request' && (failure() || success())
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflow_url = `https://github.com/${context.repo.owner}/${context.repo.name}/actions/runs/${context.runId}`;
            const status = process.env.STATUS || (job.status === 'success' ? '✅' : '❌');
            const message = `## Lint Results ${status}\n\nDetailed results: [View Workflow Run](${workflow_url})`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message
            }); 